/// <reference path="../scripts/typings/ripple/ripple.floor.d.ts" />
/// <reference path="../scripts/typings/jquery/jquery.d.ts" />
/// <reference path="../scripts/typings/createjs/createjs.d.ts" />
/// <reference path="../scripts/typings/angularjs/angular.d.ts" />
/// <reference path="../scripts/typings/angularjs/angular-route.d.ts" />
/// <reference path="ship.ts" />
/// <reference path="placementcontroller.ts" />
/// <reference path="app.ts" />
/// <reference path="gamecontroller.ts" />
//# sourceMappingURL=_references.js.map
